# ===== Stage 1: build =====
FROM maven:3.9-eclipse-temurin-17 AS build
WORKDIR /app

COPY pom.xml .
COPY src ./src

RUN mvn -B clean package -DskipTests

# ===== Stage 2: runtime =====
FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar

EXPOSE 5140/udp 5140/tcp 8080
ENTRYPOINT ["java","-jar","/app/app.jar"]

COPY simulator/lparstat-sample.xml          /app/samples/lparstat-sample.xml
COPY simulator/lparstat-sample-normal.xml   /app/samples/lparstat-sample-normal.xml
COPY simulator/lparstat-sample-warning.xml  /app/samples/lparstat-sample-warning.xml
COPY simulator/lparstat-sample-critical.xml /app/samples/lparstat-sample-critical.xml